### ISSUE TITLE
wget "ConnectionResetError: [Errno 104] Connection reset by peer"

### ISSUE THREAD

**Issue by RyanLiut** [raingo/TGIF-Release#12]
Hi,

    When I use the "wget" to get the data from the link, it said "ConnectionResetError: [Errno 104] Connection reset by peer". Does that mean I can't download it by the code? Is there any other automatic way to download it?

    Thank you!

**Comment by RyanLiut** [comment]
Do you have other ways of downloading the dataset? Like google drive?

**Comment by yalesong** [comment]
Try [this link](https://drive.google.com/a/vision.snu.ac.kr/file/d/11wdvsTYIPcSTRMVry1tufILiNE4aAMp5/view?usp=sharing)
