### ISSUE TITLE
tumblr_nbt7suBKo71tlr3u4o1_1280 caption fail

### ISSUE THREAD

**Issue by chaonan99** [raingo/TGIF-Release#3]
caption of video `tumblr_nbt7suBKo71tlr3u4o1_1280` is `Fail` in https://github.com/raingo/TGIF-Release/blob/master/data/tgif-v1.0.tsv . I would caption as **a man is playing guitar with a light flashing behind him**. How it happens and could you fix this in your dataset?

**Comment by raingo** [comment]
Thanks for reporting. 

This has been fixed in 3e54d2f71418d8a2e9f5f61aa5be0edb9c0ac2b8, and the right caption `A guy in red shirt playing guitar.` is in place now.

Please feel free to reopen if there are similar problems.
