### ISSUE TITLE
Getting Access Denied in HTTP response when downloading gifs

### ISSUE THREAD

**Issue by g1910** [raingo/TGIF-Release#5]
Hi

I am trying to download the TGIF data using the URLs present in the tgif-v1.0.tsv. Some of the URLs like the following ones are giving 'AccessDenied' error as http response:

https://31.media.tumblr.com/ba40409106d901d98b7def52e95c0bc9/tumblr_mhh7jhY9j71s0i1eho1_250.gif

https://33.media.tumblr.com/a336036825590ab7fe58426e4c4e942e/tumblr_mhcipcK1Dg1rbl1eco1_500.gif

Here's what I am getting as the http response:

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E0A9280A09B0C9C6</RequestId>
<HostId>
VN9c9eO6rlAntI9A44kQyu/XlBGIi2O/FE3o/6suWq/zfLGNNalQ7Xa6WYNj808+jT6xKpU1q2I=
</HostId>
</Error>`

Please look into it!

Thanks

**Comment by raingo** [comment]
Thanks for reporting this issue.

It's inevitable that some GIFs will be deleted overtime by the users, but we will figure out a way to release the original GIFs for academic use. I will comment on this thread, once we know how to do it.

Thanks

**Comment by g1910** [comment]
You must be having the dataset with you. If you can just host it somewhere, we can download it from there. 

It would be nice if you could do it asap as we are trying to work on a problem statement involving the gifs and this seems to be the best source for us to experiment with. :)

**Comment by g1910** [comment]
I just crunched some statistics on the number of usable GIFs that could be derived from the URLs. I have downloaded from some 10,000 URLs and it's astonishing that I got just around 2700 GIFs and the rest simply returned an error response!! This is a serious concern as it will become an impediment for us to carry out any empirical analysis.

The dataset you have created and the study you have performed is commendable but it's equally important to make the dataset public at the earliest so as to promote further research and citations. Please look into this as soon as possible.

Thanks in advance!

**Comment by g1910** [comment]
One of the co-authors of the paper, Yale Song, mailed me few hours ago with an alternative way to download the GIFs. It's working perfectly and I am now able to download all the gifs without any issue. :D

Thank you so much for a quick response. I really appreciate it! :)

**Comment by yalesong** [comment]
Glad it worked out. For others who have the same issue: Please contact me in person. 

We are actively working on resolving this issue, and will update a patch here as soon as it's done.
