### ISSUE TITLE
Caffe doesn't compile with caffe-rnn patch

### ISSUE THREAD

**Issue by tejus-gupta** [raingo/TGIF-Release#6]
I get the following error on compiling caffe - 
```caffe.proto:399:50: Field number 140 has already been used in "caffe.LayerParameter" by field "elu_param".```

I think it's because src/caffe/proto/caffe.proto already has ```optional ELUParameter elu_param = 140;``` but caffe-rnn.patch adds this line - ```optional TempoCropParameter tempo_crop_param = 140;```.

**Comment by tejus-gupta** [comment]
Also you have defined the following functions in net.cpp but haven't added them to net.hpp
```
void CopyTrainedLayersByName(const NetParameter& param); 
void CopyTrainedLayersFrom(std::string, bool);
void CopyTrainedLayersFromBinaryProto(std::string, bool);
```

**Comment by raingo** [comment]
This repo is not going to support merging with `caffe-rnn` branch, but as you already figured out, it should be an easy fix. Let us know if you need any help with that.

**Comment by tejus-gupta** [comment]
I have compiled caffe. Can you give please explain how to run the baseline model on my gif? It seems that some files are missing e.g, cnn.prototxt, cnn-mean.npy, vocab.

 Thanks for the help.

**Comment by raingo** [comment]
Please refer to `https://github.com/raingo/TGIF-Release/tree/master/code/gif2txt-lstm
