### ISSUE TITLE
which version of caffe do you use?

### ISSUE THREAD

**Issue by duzani** [raingo/TGIF-Release#7]
I'm having endless error while trying to run your code, and I think it is because the version of caffe I'm using doesn't match with your caffe version.
please let me know:)

* My current caffe version is '1.0-14-g4efdf7e'

**Comment by raingo** [comment]
Please refer to `https://github.com/raingo/TGIF-Release/blob/master/code/gif2txt-lstm/README.md` to get the right caffe version.

Thanks!

**Comment by duzani** [comment]
Thank you for kind comment, raingo!
