### ISSUE TITLE
Question about the dataset :)

### ISSUE THREAD

**Issue by duzani** [raingo/TGIF-Release#8]
Hello, raingo!
I'm a student majoring in CS.
I was trying to run your code, and I have a question.

In your code **'compile-data.py'** , which prepares the datasets like test.pkl, val.pkl,... 
I cannot find the files '**LSMDC15_annos_test.csv**', **'LSMDC15_annos_val.csv**', **'LSMDC15_annos_training.csv'**, **'LSMDC15_annos_all.csv'** in your github.

also, what is the path, 
**jpg_path = '/homes/ycli/data-bank/M-VAD-aligned/LSMDC/jpg'**,  and
**avis_path =  '/homes/ycli/data-bank/M-VAD-aligned/LSMDC/avis'** ?

I cannot find such pathes and files in your github. So I have no idea how to run it....
Thank you for reading!

**Comment by raingo** [comment]
I think those for the the LSMDC15 datasets, which are not supported. Please ignore those parts. Let me know if you found further issues.
